name: Deploy Vidly

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: installing packages
        run: npm i
      - name: Build React App
        run: npm run build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build --domain kashif-ghafoor-vidly.surge.sh --token ${{ secrets.SURGE_TOKEN }}
